// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

/*
Package transport is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	TodoRequest
	TodoResponse
	Todo
*/
package transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateResponse struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type TodoRequest struct {
}

func (m *TodoRequest) Reset()                    { *m = TodoRequest{} }
func (m *TodoRequest) String() string            { return proto.CompactTextString(m) }
func (*TodoRequest) ProtoMessage()               {}
func (*TodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TodoResponse struct {
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *TodoResponse) Reset()                    { *m = TodoResponse{} }
func (m *TodoResponse) String() string            { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()               {}
func (*TodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TodoResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type Todo struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "transport.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "transport.CreateResponse")
	proto.RegisterType((*TodoRequest)(nil), "transport.TodoRequest")
	proto.RegisterType((*TodoResponse)(nil), "transport.TodoResponse")
	proto.RegisterType((*Todo)(nil), "transport.Todo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoService service

type TodoServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Todos(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/transport.TodoService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Todos(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/transport.TodoService/Todos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Todos(context.Context, *TodoRequest) (*TodoResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TodoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Todos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Todos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.TodoService/Todos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Todos(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transport.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TodoService_Create_Handler,
		},
		{
			MethodName: "Todos",
			Handler:    _TodoService_Todos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xdd, 0x2e, 0xec, 0xac, 0xbb, 0x42, 0x10, 0xad, 0x9e, 0x4a, 0xa4, 0xe0, 0x41,
	0x7a, 0xa8, 0x14, 0xbc, 0x78, 0xf2, 0x0d, 0xaa, 0x2f, 0x50, 0x9b, 0x41, 0x02, 0xd2, 0x89, 0xc9,
	0xe8, 0x23, 0xf8, 0xdc, 0xd2, 0x24, 0x6a, 0x75, 0x7b, 0xfc, 0x33, 0xff, 0x7c, 0xf9, 0x12, 0x80,
	0x17, 0x67, 0x87, 0xda, 0x3a, 0x62, 0x92, 0x1b, 0x76, 0xfd, 0xe8, 0x2d, 0x39, 0x56, 0x15, 0xec,
	0x1e, 0x1c, 0xf6, 0x8c, 0x1d, 0xbe, 0xbd, 0xa3, 0x67, 0x79, 0x0a, 0x39, 0x1b, 0x7e, 0xc5, 0x42,
	0x94, 0xe2, 0x7a, 0xd3, 0xc5, 0xa0, 0x5a, 0xd8, 0x7f, 0xd7, 0xbc, 0xa5, 0xd1, 0xa3, 0xbc, 0x82,
	0x15, 0x93, 0xa6, 0x50, 0xdb, 0x36, 0x27, 0xf5, 0x0f, 0xb2, 0x7e, 0x22, 0x4d, 0x5d, 0x18, 0xaa,
	0x1d, 0x6c, 0x43, 0x8a, 0x6c, 0xd5, 0xc2, 0x71, 0x8c, 0x89, 0x51, 0x41, 0x3e, 0xd5, 0x7c, 0x21,
	0xca, 0xa3, 0x25, 0x48, 0x9c, 0xaa, 0x1b, 0x58, 0x4d, 0x51, 0xee, 0x21, 0x33, 0x3a, 0x79, 0x65,
	0x46, 0xff, 0xaa, 0x66, 0x33, 0xd5, 0xe6, 0x53, 0xc4, 0x4b, 0x1f, 0xd1, 0x7d, 0x98, 0x01, 0xe5,
	0x3d, 0xac, 0xa3, 0xba, 0x2c, 0x66, 0xfc, 0x3f, 0x8f, 0xbe, 0xbc, 0x58, 0x98, 0x24, 0xc7, 0x3b,
	0xc8, 0x27, 0x9a, 0x97, 0x67, 0xff, 0xed, 0xd2, 0xee, 0xf9, 0xc1, 0x79, 0xdc, 0x7c, 0x5e, 0x87,
	0xcf, 0xbe, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x51, 0x44, 0xdd, 0x1b, 0x7a, 0x01, 0x00, 0x00,
}
